// Blog data — UrgiMed. Posts follow the winning pattern: question-led titles, medical reviewer, date, FAQ block, internal links.
const BLOG_CATEGORIES = [
  { id: 'car-accident', en: 'Car Accident', es: 'Accidente de Auto' },
  { id: 'pip', en: 'PIP Insurance', es: 'Seguro PIP' },
  { id: 'whiplash', en: 'Whiplash & Neck', es: 'Latigazo y Cuello' },
  { id: 'concussion', en: 'Concussion', es: 'Conmoción' },
  { id: 'slip-fall', en: 'Slip & Fall', es: 'Caídas' },
  { id: 'work', en: 'Work Injury', es: 'Lesión Laboral' },
  { id: 'chiro', en: 'Chiropractic', es: 'Quiropráctica' },
  { id: 'pain', en: 'Pain Management', es: 'Manejo del Dolor' },
  { id: 'news', en: 'UrgiMed News', es: 'Noticias UrgiMed' },
];
const BLOG_POSTS = [
  { slug: 'florida-14-day-rule-car-accident', seoTitle: 'Florida’s 14-Day Rule After a Car Accident', cat: 'pip', date: '2026-09-18', reviewer: 'mario-r-perez', img: 'img/w-car-accident.jpg', featured: true, read: 6,
    title: { en: 'Florida’s 14-Day Rule: What Happens If You Wait to See a Doctor After a Car Accident', es: 'La Regla de 14 Días de Florida: Qué Pasa Si Espera Para Ver a un Médico Tras un Accidente' },
    excerpt: { en: 'Under Florida’s PIP law you have 14 days from the crash to get medical care or you may lose up to $10,000 in benefits. Here is exactly how the rule works and what counts.', es: 'Bajo la ley PIP de Florida tiene 14 días desde el choque para recibir atención médica o podría perder hasta $10,000 en beneficios. Así funciona la regla exactamente.' },
    body: { en: [
      ['h2', 'What the 14-day rule says'], ['p', 'Florida Statute 627.736 requires anyone injured in a motor vehicle accident to receive initial medical treatment within 14 days of the crash to be eligible for Personal Injury Protection (PIP) benefits. Miss the window and your own insurer can deny every medical bill related to the accident, no matter how serious the injury turns out to be.'],
      ['h2', 'Who counts as a “doctor” for the 14-day rule?'], ['p', 'The statute lists who can provide the initial care: a medical doctor (MD), osteopathic physician (DO), dentist, chiropractor, or a hospital, emergency department or licensed urgent care. A massage therapist or acupuncturist does not count. UrgiMed clinics are staffed by MDs, DOs and chiropractors, so a visit to any of our 11 locations satisfies the rule.'],
      ['h2', 'Why the $10,000 depends on an EMC'], ['p', 'PIP pays up to $10,000 only if a physician determines you have an Emergency Medical Condition (EMC). Without that determination, benefits are capped at $2,500. The EMC decision must be made by an MD, DO, dentist, physician assistant or advanced practice nurse — a chiropractor alone cannot certify it. At UrgiMed the same first visit includes the exam, imaging and EMC determination, so the paperwork your insurer needs is complete on day one.'],
      ['h2', 'I feel fine. Should I still go?'], ['p', 'Yes. Adrenaline masks pain for 24–72 hours, and whiplash, disc injuries and concussion symptoms commonly appear days later. Getting examined inside the window protects your benefits even if symptoms show up in week two.'],
      ['h2', 'What to bring to your first visit'], ['ul', ['Photo ID and auto insurance card', 'Police or crash report number', 'Photos of the vehicles and any visible injuries', 'A list of symptoms, even minor ones', 'Your attorney’s contact information, if you have one']],
      ['cta', 'car-accident'],
    ], es: [
      ['h2', 'Qué dice la regla de 14 días'], ['p', 'El Estatuto 627.736 de Florida exige que cualquier persona lesionada en un accidente vehicular reciba tratamiento médico inicial dentro de 14 días del choque para ser elegible a los beneficios de Protección de Lesiones Personales (PIP). Si pasa el plazo, su propia aseguradora puede negar todas las facturas médicas relacionadas con el accidente.'],
      ['h2', '¿Quién cuenta como “médico”?'], ['p', 'El estatuto incluye: médico (MD), médico osteópata (DO), dentista, quiropráctico, o un hospital, sala de emergencias o centro de urgencias con licencia. UrgiMed cuenta con MDs, DOs y quiroprácticos, así que una visita a cualquiera de nuestras 11 clínicas cumple la regla.'],
      ['h2', 'Por qué los $10,000 dependen de una EMC'], ['p', 'El PIP paga hasta $10,000 solo si un médico determina que usted tiene una Condición Médica de Emergencia (EMC). Sin esa determinación, el límite es $2,500. En UrgiMed la primera visita incluye el examen, las imágenes y la determinación EMC.'],
      ['h2', 'Me siento bien. ¿Debo ir de todos modos?'], ['p', 'Sí. La adrenalina oculta el dolor durante 24–72 horas, y los síntomas de latigazo, disco y conmoción suelen aparecer días después. Ser examinado dentro del plazo protege sus beneficios.'],
      ['h2', 'Qué llevar a su primera visita'], ['ul', ['Identificación y tarjeta de seguro de auto', 'Número del reporte policial', 'Fotos de los vehículos y lesiones visibles', 'Lista de síntomas, incluso leves', 'Contacto de su abogado, si tiene uno']],
      ['cta', 'car-accident'],
    ] },
    faq: { en: [['Does the 14-day rule apply to passengers?', 'Yes. Passengers, pedestrians and cyclists hit by a vehicle are all subject to the same 14-day requirement.'], ['Does an ER visit count?', 'Yes, an emergency room visit satisfies the rule, but you still need follow-up care and an EMC determination to unlock the full $10,000.'], ['What if the accident was not my fault?', 'PIP is no-fault coverage: your own policy pays first regardless of who caused the crash, so the 14-day rule still applies.']], es: [['¿Aplica la regla a pasajeros?', 'Sí. Pasajeros, peatones y ciclistas golpeados por un vehículo están sujetos al mismo plazo.'], ['¿Cuenta una visita a emergencias?', 'Sí, pero aún necesita seguimiento y una determinación EMC para obtener los $10,000 completos.'], ['¿Y si el accidente no fue mi culpa?', 'El PIP es sin culpa: su propia póliza paga primero sin importar quién causó el choque, así que la regla aplica igual.']] } },
  { slug: 'how-long-does-whiplash-last', seoTitle: 'How Long Does Whiplash Last?', cat: 'whiplash', date: '2026-09-04', reviewer: 'james-manzanares', img: 'img/whiplash-brace.jpg', read: 7,
    title: { en: 'How Long Does Whiplash Last? Recovery Timeline and When to Worry', es: '¿Cuánto Dura el Latigazo Cervical? Tiempos de Recuperación y Cuándo Preocuparse' },
    excerpt: { en: 'Most whiplash improves within 6–12 weeks, but 1 in 3 people still have symptoms a year later. Learn the stages of recovery and the red flags that mean you need imaging.', es: 'La mayoría de los latigazos mejoran en 6–12 semanas, pero 1 de cada 3 personas sigue con síntomas un año después. Conozca las etapas y las señales de alarma.' },
    body: { en: [
      ['h2', 'What whiplash actually is'], ['p', 'Whiplash is a sprain of the neck’s ligaments and muscles caused by a rapid back-and-forth motion — most often a rear-end collision at speeds as low as 5–10 mph. The cervical spine is forced into an S-shape, stretching soft tissue beyond its limit and sometimes injuring the discs and facet joints.'],
      ['h2', 'Typical recovery timeline'], ['ul', ['Days 1–3: stiffness and pain build as inflammation peaks', 'Weeks 1–2: gentle motion and chiropractic care reduce muscle guarding', 'Weeks 3–6: physical therapy restores range of motion and strength', 'Weeks 6–12: most patients return to normal activity', 'Beyond 3 months: chronic whiplash-associated disorder, seen in roughly one third of cases']],
      ['h2', 'Red flags that need imaging now'], ['ul', ['Numbness, tingling or weakness in the arms or hands', 'Severe headache at the base of the skull', 'Dizziness, blurred vision or trouble swallowing', 'Pain that worsens at night or wakes you up']],
      ['h2', 'How UrgiMed treats whiplash'], ['p', 'X-ray on the first visit rules out fracture and instability. Chiropractic adjustments and cold laser calm the acute phase; physical therapy rebuilds motion; and when pain radiates, our orthopedic and pain management physicians evaluate for disc injury and offer injections. Every visit is documented for your PIP claim.'],
      ['cta', 'whiplash'],
    ], es: [
      ['h2', 'Qué es realmente el latigazo cervical'], ['p', 'El latigazo es un esguince de los ligamentos y músculos del cuello causado por un movimiento rápido hacia atrás y adelante, casi siempre en una colisión trasera incluso a 5–10 mph.'],
      ['h2', 'Tiempos típicos de recuperación'], ['ul', ['Días 1–3: la rigidez y el dolor aumentan', 'Semanas 1–2: movimiento suave y quiropráctica', 'Semanas 3–6: la terapia física restaura movimiento y fuerza', 'Semanas 6–12: la mayoría vuelve a la normalidad', 'Más de 3 meses: trastorno crónico, en un tercio de los casos']],
      ['h2', 'Señales de alarma'], ['ul', ['Entumecimiento u hormigueo en brazos o manos', 'Dolor de cabeza intenso en la base del cráneo', 'Mareos, visión borrosa o dificultad para tragar', 'Dolor que empeora de noche']],
      ['h2', 'Cómo trata UrgiMed el latigazo'], ['p', 'Rayos X en la primera visita, quiropráctica y láser frío en la fase aguda, terapia física para recuperar movimiento, y evaluación ortopédica y de manejo del dolor cuando el dolor se irradia.'],
      ['cta', 'whiplash'],
    ] },
    faq: { en: [['Can whiplash show up days later?', 'Yes. Symptoms commonly begin 24–72 hours after the crash.'], ['Should I wear a neck collar?', 'Usually no. Current guidelines favor early gentle movement over immobilization.'], ['Is whiplash covered by PIP?', 'Yes, if you are seen within 14 days of the accident.']], es: [['¿Puede aparecer días después?', 'Sí. Los síntomas suelen comenzar 24–72 horas tras el choque.'], ['¿Debo usar collarín?', 'Normalmente no. Las guías actuales favorecen el movimiento suave temprano.'], ['¿Lo cubre el PIP?', 'Sí, si lo atienden dentro de 14 días.']] } },
  { slug: 'common-car-accident-injuries', seoTitle: '7 Common Car Accident Injuries & Symptoms', cat: 'car-accident', date: '2026-08-21', reviewer: 'gregory-schwaid', img: 'img/crash-scene-neck.jpg', read: 8,
    title: { en: '7 Common Car Accident Injuries and the Symptoms They Cause', es: '7 Lesiones Comunes en Accidentes de Auto y Sus Síntomas' },
    excerpt: { en: 'From whiplash and concussion to herniated discs and seat-belt injuries: the injuries we diagnose most often at our 11 Florida clinics, and the symptoms to watch for.', es: 'Desde latigazo y conmoción hasta discos herniados y lesiones por cinturón: las lesiones que más diagnosticamos y los síntomas a vigilar.' },
    body: { en: [
      ['h2', '1. Whiplash'], ['p', 'Neck pain and stiffness, headaches at the base of the skull, shoulder pain. The most common crash injury, present in the majority of rear-end collisions.'],
      ['h2', '2. Concussion'], ['p', 'You do not have to hit your head. The brain moving inside the skull is enough. Watch for fogginess, sensitivity to light, nausea, trouble concentrating and irritability.'],
      ['h2', '3. Herniated disc'], ['p', 'Pain radiating into an arm or leg, numbness, weakness. Often missed in the ER and diagnosed weeks later when symptoms persist.'],
      ['h2', '4. Seat-belt and chest injuries'], ['p', 'Bruised ribs, sternum pain and abdominal tenderness. Persistent chest pain after a crash always needs evaluation.'],
      ['h2', '5. Knee and shoulder injuries'], ['p', 'Knees strike the dashboard; shoulders absorb the belt. Meniscus tears and rotator cuff injuries are common.'],
      ['h2', '6. Wrist and hand fractures'], ['p', 'Bracing against the steering wheel loads the wrist. Swelling and pain with gripping are typical.'],
      ['h2', '7. Psychological trauma'], ['p', 'Fear of driving, sleep problems and anxiety are real injuries. Our psychology team evaluates and documents them alongside physical care.'],
      ['cta', 'car-accident'],
    ], es: [
      ['h2', '1. Latigazo cervical'], ['p', 'Dolor y rigidez de cuello, dolores de cabeza, dolor de hombro. La lesión más común.'],
      ['h2', '2. Conmoción'], ['p', 'No hace falta golpearse la cabeza. Confusión, sensibilidad a la luz, náuseas y dificultad para concentrarse.'],
      ['h2', '3. Disco herniado'], ['p', 'Dolor irradiado a un brazo o pierna, entumecimiento, debilidad.'],
      ['h2', '4. Lesiones por cinturón y tórax'], ['p', 'Costillas magulladas, dolor en el esternón. El dolor de pecho persistente siempre requiere evaluación.'],
      ['h2', '5. Rodilla y hombro'], ['p', 'Desgarros de menisco y manguito rotador son frecuentes.'],
      ['h2', '6. Fracturas de muñeca y mano'], ['p', 'Hinchazón y dolor al agarrar.'],
      ['h2', '7. Trauma psicológico'], ['p', 'Miedo a conducir, insomnio y ansiedad son lesiones reales que evaluamos y documentamos.'],
      ['cta', 'car-accident'],
    ] },
    faq: { en: [['Which injuries show up late?', 'Whiplash, concussion and disc injuries commonly appear 1–3 days after the crash.'], ['Do I need an MRI?', 'Not always. X-ray and ultrasound on the first visit catch most injuries; we order MRI when nerve symptoms persist.']], es: [['¿Qué lesiones aparecen tarde?', 'Latigazo, conmoción y lesiones de disco suelen aparecer 1–3 días después.'], ['¿Necesito resonancia?', 'No siempre. Rayos X y ultrasonido detectan la mayoría; pedimos MRI si persisten síntomas nerviosos.']] } },
  { slug: 'concussion-symptoms-after-car-accident', seoTitle: 'Concussion Symptoms After a Car Accident', cat: 'concussion', date: '2026-08-07', reviewer: 'allamm-morales', img: 'img/w-receptionist.jpg', read: 6,
    title: { en: 'Concussion After a Car Accident: Symptoms That Can Appear Days Later', es: 'Conmoción Tras un Accidente de Auto: Síntomas Que Pueden Aparecer Días Después' },
    excerpt: { en: 'You can have a concussion without hitting your head or losing consciousness. A neurologist explains the delayed symptoms and why early evaluation matters.', es: 'Puede tener una conmoción sin golpearse la cabeza ni perder el conocimiento. Un neurólogo explica los síntomas tardíos.' },
    body: { en: [
      ['h2', 'How a crash causes a concussion without impact'], ['p', 'The sudden deceleration of a collision makes the brain shift inside the skull. That movement stretches nerve fibers and disrupts normal signaling — a mild traumatic brain injury — even if your head never touched anything.'],
      ['h2', 'Symptoms to watch for in the first two weeks'], ['ul', ['Headache that does not respond to over-the-counter medication', 'Feeling “foggy” or slowed down', 'Sensitivity to light and noise', 'Dizziness or balance problems', 'Sleeping more or less than usual', 'Irritability, anxiety or sadness', 'Trouble remembering new information']],
      ['h2', 'Why documentation matters'], ['p', 'Concussion symptoms are invisible on X-ray, so the medical record is the evidence. A neurological evaluation at UrgiMed documents cognitive, balance and visual findings, establishes an Emergency Medical Condition where appropriate, and starts a recovery plan.'],
      ['cta', 'concussion'],
    ], es: [
      ['h2', 'Cómo un choque causa conmoción sin impacto'], ['p', 'La desaceleración súbita hace que el cerebro se mueva dentro del cráneo, estirando fibras nerviosas, incluso si la cabeza no tocó nada.'],
      ['h2', 'Síntomas en las primeras dos semanas'], ['ul', ['Dolor de cabeza que no responde a analgésicos', 'Sensación de “niebla” mental', 'Sensibilidad a la luz y al ruido', 'Mareos o problemas de equilibrio', 'Dormir más o menos de lo normal', 'Irritabilidad, ansiedad o tristeza', 'Dificultad para recordar']],
      ['h2', 'Por qué importa la documentación'], ['p', 'La conmoción no se ve en rayos X; el expediente médico es la evidencia. Una evaluación neurológica en UrgiMed documenta los hallazgos y establece la EMC cuando corresponde.'],
      ['cta', 'concussion'],
    ] },
    faq: { en: [['How long does a concussion last?', 'Most resolve in 2–4 weeks; symptoms lasting longer need neurological follow-up.'], ['Can I drive with a concussion?', 'Not until a physician clears you — reaction time and attention are impaired.']], es: [['¿Cuánto dura una conmoción?', 'La mayoría se resuelve en 2–4 semanas.'], ['¿Puedo conducir?', 'No hasta que un médico lo autorice.']] } },
  { slug: 'where-to-go-after-car-accident-florida', seoTitle: 'Where to Go After a Car Accident in Florida', cat: 'car-accident', date: '2026-07-24', reviewer: 'mario-r-perez', img: 'img/w-facade.jpg', read: 5,
    title: { en: 'ER, Urgent Care or Injury Clinic? Where to Go After a Car Accident in Florida', es: '¿Emergencias, Urgencias o Clínica de Lesiones? Dónde Ir Tras un Accidente en Florida' },
    excerpt: { en: 'Each option has a role. Here is how to choose, what each one costs, and why most crash victims end up needing an injury clinic anyway.', es: 'Cada opción tiene su papel. Cómo elegir, qué cuesta cada una y por qué la mayoría termina necesitando una clínica de lesiones.' },
    body: { en: [
      ['h2', 'Go to the ER if…'], ['ul', ['You lost consciousness, are bleeding heavily or suspect a broken bone', 'You have chest pain, shortness of breath or abdominal pain', 'You cannot move a limb or feel numbness on one side']],
      ['h2', 'Urgent care is fine for…'], ['p', 'Cuts, minor sprains and a quick check when the ER is not needed. Note that urgent care rarely provides the follow-up treatment, imaging review or EMC determination your PIP claim requires.'],
      ['h2', 'An injury clinic is built for the rest'], ['p', 'Most crash injuries — whiplash, back pain, headaches, numbness — are not emergencies but do need weeks of treatment and careful documentation. UrgiMed combines the physician exam, X-ray, chiropractic, physical therapy and pain management in one place, bills PIP directly and coordinates with your attorney. Same-day appointments at 11 Florida clinics.'],
      ['cta', 'car-accident'],
    ], es: [
      ['h2', 'Vaya a emergencias si…'], ['ul', ['Perdió el conocimiento, sangra mucho o sospecha una fractura', 'Tiene dolor de pecho, falta de aire o dolor abdominal', 'No puede mover una extremidad o siente entumecimiento en un lado']],
      ['h2', 'Urgencias sirve para…'], ['p', 'Cortes, esguinces leves y una revisión rápida. Rara vez ofrecen el seguimiento ni la determinación EMC que su reclamo PIP requiere.'],
      ['h2', 'La clínica de lesiones es para el resto'], ['p', 'La mayoría de las lesiones por choque no son emergencias, pero necesitan semanas de tratamiento y documentación. UrgiMed combina todo en un lugar, factura al PIP y coordina con su abogado.'],
      ['cta', 'car-accident'],
    ] },
    faq: { en: [['Will the ER bill my PIP?', 'Yes, but ER visits often consume a large share of the $10,000 quickly.'], ['Can I go to UrgiMed after the ER?', 'Yes — that is the most common path. Bring your discharge papers.']], es: [['¿Emergencias factura al PIP?', 'Sí, pero suele consumir gran parte de los $10,000 rápidamente.'], ['¿Puedo ir a UrgiMed después de emergencias?', 'Sí, es el camino más común. Traiga sus papeles de alta.']] } },
  { slug: 'slip-and-fall-what-to-do', seoTitle: 'What to Do After a Slip and Fall', cat: 'slip-fall', date: '2026-07-10', reviewer: 'alexandra-carrer', img: 'img/w-slip-and-fall.jpg', read: 6,
    title: { en: 'Hurt in a Slip and Fall? 6 Steps to Protect Your Health and Your Claim', es: '¿Se Lastimó en una Caída? 6 Pasos Para Proteger Su Salud y Su Reclamo' },
    excerpt: { en: 'Falls in stores, parking lots and rentals are the most disputed injury claims. An orthopedic surgeon explains what to do in the first 48 hours.', es: 'Las caídas en tiendas, estacionamientos y alquileres son los reclamos más disputados. Qué hacer en las primeras 48 horas.' },
    body: { en: [
      ['h2', '1. Report it before you leave'], ['p', 'Ask for a manager and make sure an incident report is written. Get a copy or a photo of it.'],
      ['h2', '2. Photograph the hazard'], ['p', 'Wet floor, broken step, missing handrail, poor lighting — photograph it and the absence of warning signs before it is cleaned up.'],
      ['h2', '3. Get names of witnesses'], ['p', 'Even a first name and phone number helps.'],
      ['h2', '4. See a doctor the same day'], ['p', 'Hip, wrist and tailbone fractures and shoulder tears are common and often underestimated. An orthopedic exam with X-ray creates the dated record your claim depends on.'],
      ['h2', '5. Follow the treatment plan'], ['p', 'Gaps in care are the first thing an insurer uses to dispute a claim.'],
      ['h2', '6. Keep everything'], ['p', 'Shoes you were wearing, receipts, photos and every medical document.'],
      ['cta', 'slip-and-fall'],
    ], es: [
      ['h2', '1. Repórtelo antes de irse'], ['p', 'Pida un gerente y asegúrese de que se escriba un reporte de incidente.'],
      ['h2', '2. Fotografíe el peligro'], ['p', 'Piso mojado, escalón roto, barandal faltante, y la ausencia de señales de advertencia.'],
      ['h2', '3. Anote testigos'], ['p', 'Un nombre y teléfono bastan.'],
      ['h2', '4. Vea a un médico el mismo día'], ['p', 'Fracturas de cadera, muñeca y coxis son comunes. Un examen ortopédico con rayos X crea el registro fechado.'],
      ['h2', '5. Siga el plan de tratamiento'], ['p', 'Las interrupciones en la atención son lo primero que usa la aseguradora para disputar.'],
      ['h2', '6. Guarde todo'], ['p', 'Zapatos, recibos, fotos y cada documento médico.'],
      ['cta', 'slip-and-fall'],
    ] },
    faq: { en: [['Does PIP cover a slip and fall?', 'No. Falls are covered by the property owner’s liability insurance or your health plan. We accept Letters of Protection.'], ['How long do I have to file in Florida?', 'Generally two years for negligence claims. Confirm with an attorney.']], es: [['¿El PIP cubre una caída?', 'No. Las cubre el seguro de responsabilidad del propietario o su plan de salud. Aceptamos Cartas de Protección.'], ['¿Cuánto tiempo tengo para reclamar?', 'Generalmente dos años. Confirme con un abogado.']] } },
  { slug: 'workers-comp-doctor-florida', seoTitle: 'Choosing a Workers’ Comp Doctor in Florida', cat: 'work', date: '2026-06-19', reviewer: 'gregory-schwaid', img: 'img/w-work-injury.jpg', read: 6,
    title: { en: 'Injured at Work in Florida? How to Choose Your Workers’ Comp Doctor', es: '¿Se Lesionó en el Trabajo en Florida? Cómo Elegir Su Médico de Compensación Laboral' },
    excerpt: { en: 'In Florida your employer’s insurer usually picks the treating physician — but you have more say than you think. Here is how the process works.', es: 'En Florida la aseguradora de su empleador suele elegir al médico, pero usted tiene más voz de lo que cree.' },
    body: { en: [
      ['h2', 'Report the injury within 30 days'], ['p', 'Florida law requires you to notify your employer within 30 days. Do it in writing the same day if possible.'],
      ['h2', 'Who chooses the doctor'], ['p', 'The employer or its carrier authorizes the treating physician. You can request a specific provider — ask for UrgiMed by name — and you are entitled to one change of physician during the claim.'],
      ['h2', 'What the doctor must provide'], ['p', 'DWC-25 forms after each visit, work-status restrictions, and progress reports to the adjuster. Missing or late forms delay your benefits; our staff handles them for you.'],
      ['h2', 'Treatment at UrgiMed'], ['p', 'Orthopedic evaluation, on-site X-ray, chiropractic, physical therapy and pain management, with bilingual staff at every clinic.'],
      ['cta', 'work-injury'],
    ], es: [
      ['h2', 'Reporte la lesión en 30 días'], ['p', 'La ley de Florida exige notificar a su empleador en 30 días. Hágalo por escrito el mismo día.'],
      ['h2', 'Quién elige al médico'], ['p', 'El empleador o su aseguradora autoriza al médico. Puede pedir UrgiMed por nombre y tiene derecho a un cambio de médico durante el reclamo.'],
      ['h2', 'Qué debe entregar el médico'], ['p', 'Formularios DWC-25, restricciones laborales e informes al ajustador. Nuestro personal los gestiona por usted.'],
      ['h2', 'Tratamiento en UrgiMed'], ['p', 'Evaluación ortopédica, rayos X, quiropráctica, terapia física y manejo del dolor, con personal bilingüe.'],
      ['cta', 'work-injury'],
    ] },
    faq: { en: [['Do I pay anything?', 'No. Authorized workers’ comp treatment has no co-pay.'], ['Can I be fired for filing?', 'Retaliation for a workers’ comp claim is illegal in Florida.']], es: [['¿Pago algo?', 'No. El tratamiento autorizado no tiene copago.'], ['¿Pueden despedirme por reclamar?', 'Las represalias por un reclamo son ilegales en Florida.']] } },
  { slug: 'chiropractor-after-car-accident', seoTitle: 'Chiropractor After a Car Accident', cat: 'chiro', date: '2026-06-05', reviewer: 'mario-r-perez', img: 'img/w-pt-medium.jpg', read: 5,
    title: { en: 'Should You See a Chiropractor After a Car Accident? What the Evidence Says', es: '¿Debe Ver a un Quiropráctico Tras un Accidente de Auto? Qué Dice la Evidencia' },
    excerpt: { en: 'Chiropractic care is the most common first treatment after a crash. Here is what it helps, when it is combined with medical care, and how it affects your PIP claim.', es: 'La quiropráctica es el tratamiento inicial más común tras un choque. Qué ayuda, cuándo se combina con atención médica y cómo afecta su reclamo PIP.' },
    body: { en: [
      ['h2', 'What chiropractic treats well'], ['p', 'Whiplash, mechanical neck and back pain, and joint stiffness respond well to adjustment combined with soft-tissue work. Studies show faster return of range of motion than rest alone.'],
      ['h2', 'Why medical co-management matters'], ['p', 'A chiropractor can satisfy the 14-day rule but cannot certify an Emergency Medical Condition. At UrgiMed an MD or DO evaluates you on the same visit, so your PIP limit is $10,000 rather than $2,500.'],
      ['h2', 'What to expect'], ['p', 'X-ray first, then gentle mobilization in the acute phase, progressing to adjustments and rehabilitative exercise. Most plans run 6–12 weeks with re-evaluation every 30 days.'],
      ['cta', 'chiropractic'],
    ], es: [
      ['h2', 'Qué trata bien la quiropráctica'], ['p', 'Latigazo, dolor mecánico de cuello y espalda y rigidez articular responden bien a los ajustes combinados con trabajo de tejidos blandos.'],
      ['h2', 'Por qué importa el co-manejo médico'], ['p', 'Un quiropráctico cumple la regla de 14 días pero no puede certificar la EMC. En UrgiMed un MD o DO le evalúa en la misma visita, así su límite PIP es $10,000 y no $2,500.'],
      ['h2', 'Qué esperar'], ['p', 'Rayos X primero, movilización suave, luego ajustes y ejercicio. Planes de 6–12 semanas con reevaluación cada 30 días.'],
      ['cta', 'chiropractic'],
    ] },
    faq: { en: [['Is it safe right after a crash?', 'Yes, once X-ray rules out fracture or instability.'], ['Does PIP cover chiropractic?', 'Yes, within the 14-day rule.']], es: [['¿Es seguro justo después del choque?', 'Sí, una vez que los rayos X descartan fractura.'], ['¿El PIP cubre la quiropráctica?', 'Sí, dentro de la regla de 14 días.']] } },
  { slug: 'back-pain-after-car-accident', seoTitle: 'Back Pain After a Car Accident', cat: 'pain', date: '2026-05-22', reviewer: 'abraham-josiah-fura', img: 'img/w-cold-laser-1.jpg', read: 6,
    title: { en: 'Back Pain After a Car Accident: When Is It a Herniated Disc?', es: 'Dolor de Espalda Tras un Accidente: ¿Cuándo Es un Disco Herniado?' },
    excerpt: { en: 'A pain medicine physician explains the difference between a muscle strain and a disc injury, and the treatment options short of surgery.', es: 'Un médico del dolor explica la diferencia entre una distensión muscular y una lesión de disco, y las opciones antes de la cirugía.' },
    body: { en: [
      ['h2', 'Strain vs. disc: the telltale signs'], ['ul', ['Strain: localized ache, worse with movement, improves in 2–4 weeks', 'Disc: pain that shoots into a leg or arm, numbness, tingling, weakness, worse with sitting or coughing']],
      ['h2', 'How we diagnose it'], ['p', 'Physical exam, X-ray and nerve conduction testing on site; MRI when radiating symptoms persist beyond 4–6 weeks.'],
      ['h2', 'Treatment ladder'], ['ul', ['Chiropractic and physical therapy', 'Anti-inflammatory medication and cold laser', 'Epidural steroid or facet injections under imaging guidance', 'Orthopedic surgical consult only if weakness progresses']],
      ['cta', 'pain-management'],
    ], es: [
      ['h2', 'Distensión vs. disco: las señales'], ['ul', ['Distensión: dolor localizado, mejora en 2–4 semanas', 'Disco: dolor que baja a una pierna o brazo, entumecimiento, hormigueo, debilidad']],
      ['h2', 'Cómo lo diagnosticamos'], ['p', 'Examen físico, rayos X y pruebas nerviosas en el sitio; MRI si los síntomas persisten más de 4–6 semanas.'],
      ['h2', 'Escalera de tratamiento'], ['ul', ['Quiropráctica y terapia física', 'Antiinflamatorios y láser frío', 'Inyecciones epidurales o facetarias guiadas por imagen', 'Consulta quirúrgica solo si la debilidad progresa']],
      ['cta', 'pain-management'],
    ] },
    faq: { en: [['Will I need surgery?', 'Fewer than 10% of disc injuries after a crash require surgery.'], ['How soon can I get an injection?', 'Usually after 4–6 weeks of conservative care, unless pain is severe.']], es: [['¿Necesitaré cirugía?', 'Menos del 10% de las lesiones de disco requieren cirugía.'], ['¿Cuándo puedo recibir una inyección?', 'Normalmente tras 4–6 semanas de tratamiento conservador.']] } },
  { slug: 'urgimed-primary-care-davenport', seoTitle: 'Primary Care Now at UrgiMed Davenport', cat: 'news', date: '2026-05-08', reviewer: 'mario-r-perez', img: 'img/primary-care.jpg', read: 3,
    title: { en: 'UrgiMed Davenport Now Offers Primary Care for the Whole Family', es: 'UrgiMed Davenport Ahora Ofrece Atención Primaria Para Toda la Familia' },
    excerpt: { en: 'Our headquarters on Webb Drive adds annual physicals, chronic disease management and same-week sick visits, with bilingual physicians and on-site labs.', es: 'Nuestra sede en Webb Drive añade exámenes anuales, manejo de enfermedades crónicas y visitas por enfermedad la misma semana.' },
    body: { en: [
      ['p', 'Patients who recovered from an accident with us kept asking the same question: can you be our regular doctor too? Starting this month at UrgiMed Davenport, the answer is yes.'],
      ['h2', 'What’s included'], ['ul', ['Annual physicals and preventive screenings', 'Diabetes, hypertension and cholesterol management', 'Same-week sick visits', 'Lab work and imaging on site', 'Bilingual physicians and staff']],
      ['p', 'Primary Care is available at 131 Webb Drive, Suite A, Davenport, serving Haines City, Four Corners, ChampionsGate and Poinciana. Call (407) 807-6262.'],
      ['cta', 'primary-care'],
    ], es: [
      ['p', 'Los pacientes que se recuperaron con nosotros preguntaban lo mismo: ¿pueden ser también nuestro médico de cabecera? Desde este mes en UrgiMed Davenport, la respuesta es sí.'],
      ['h2', 'Qué incluye'], ['ul', ['Exámenes anuales y preventivos', 'Manejo de diabetes, hipertensión y colesterol', 'Visitas por enfermedad la misma semana', 'Laboratorio e imágenes en el sitio', 'Médicos y personal bilingües']],
      ['p', 'Disponible en 131 Webb Drive, Suite A, Davenport. Llame al (407) 807-6262.'],
      ['cta', 'primary-care'],
    ] },
    faq: { en: [['Do you accept my health plan?', 'We accept most major plans. Call to confirm yours.']], es: [['¿Aceptan mi plan de salud?', 'Aceptamos la mayoría. Llame para confirmar.']] } },
];
const BLOG_CTA = {
  'car-accident': { to: '/injuries/car-accident', en: ['Injured in a car accident?', 'Same-day appointments at 11 Florida clinics. We document everything for your PIP claim.'], es: ['¿Lesionado en un accidente de auto?', 'Citas el mismo día en 11 clínicas. Documentamos todo para su reclamo PIP.'] },
  'whiplash': { to: '/services/chiropractic', en: ['Neck pain after a crash?', 'X-ray, chiropractic and physical therapy under one roof. Seen today.'], es: ['¿Dolor de cuello tras un choque?', 'Rayos X, quiropráctica y terapia física bajo un techo. Atención hoy.'] },
  'concussion': { to: '/services/neurology', en: ['Headaches or fog after an accident?', 'Neurological evaluation and concussion care at UrgiMed.'], es: ['¿Dolores de cabeza o confusión tras un accidente?', 'Evaluación neurológica y atención de conmoción en UrgiMed.'] },
  'slip-and-fall': { to: '/injuries/slip-and-fall', en: ['Hurt in a fall?', 'Orthopedic evaluation and X-ray the same day. Letters of Protection accepted.'], es: ['¿Se lastimó en una caída?', 'Evaluación ortopédica y rayos X el mismo día. Aceptamos Cartas de Protección.'] },
  'work-injury': { to: '/injuries/work-injury', en: ['Injured on the job?', 'We treat you and handle the workers’ comp paperwork.'], es: ['¿Se lesionó en el trabajo?', 'Le tratamos y manejamos el papeleo de compensación laboral.'] },
  'chiropractic': { to: '/services/chiropractic', en: ['Ready to start treatment?', 'Chiropractic with MD co-management at every UrgiMed clinic.'], es: ['¿Listo para empezar?', 'Quiropráctica con co-manejo médico en cada clínica UrgiMed.'] },
  'pain-management': { to: '/services/pain-management', en: ['Pain that will not quit?', 'Board-certified pain medicine, injections and nerve blocks.'], es: ['¿Dolor que no cede?', 'Medicina del dolor certificada, inyecciones y bloqueos nerviosos.'] },
  'primary-care': { to: '/services/primary-care', en: ['Need a family doctor in Davenport?', 'Primary Care at UrgiMed headquarters. Call (407) 807-6262.'], es: ['¿Necesita médico de familia en Davenport?', 'Atención Primaria en la sede de UrgiMed. Llame al (407) 807-6262.'] },
};
Object.assign(window, { BLOG_CATEGORIES, BLOG_POSTS, BLOG_CTA });
