// Extra content per injury + symptom finder data
const INJURY_EXTRA = {
  'car-accident': { services: ['xray', 'chiropractic', 'physical-therapy', 'pain-management', 'orthopedic', 'neurology', 'psychology', 'nerve'],
    symptoms: { en: ['Neck pain or stiffness', 'Headache or dizziness', 'Back pain, sciatica', 'Numbness or tingling in arms or legs', 'Shoulder, knee or wrist pain', 'Brain fog, trouble sleeping or anxiety'], es: ['Dolor o rigidez de cuello', 'Dolor de cabeza o mareos', 'Dolor de espalda, ciática', 'Entumecimiento u hormigueo en brazos o piernas', 'Dolor de hombro, rodilla o muñeca', 'Confusión mental, insomnio o ansiedad'] },
    todo: { icons: ['siren', 'camera', 'steth', 'shield', 'notebook', 'clipcheck'], en: [['Call 911 and get the crash report', 'Even for a minor crash. The report number is the first thing your insurer asks for.'], ['Photograph everything', 'Vehicles, the scene, road conditions and any visible injuries.'], ['See a doctor within 14 days', 'Florida PIP requires it. UrgiMed sees you the same day and certifies your Emergency Medical Condition.'], ['Notify your auto insurer', 'Open a PIP claim before using health insurance. We bill PIP directly.'], ['Keep a symptom diary', 'Pain often peaks 48–72 hours after the crash; note what changes.'], ['Follow your treatment plan', 'Gaps in care are the first thing an insurer uses to dispute a claim.']], es: [['Llame al 911 y obtenga el reporte', 'Incluso en un choque menor. El número del reporte es lo primero que pide su aseguradora.'], ['Fotografíe todo', 'Vehículos, la escena, el estado de la vía y las lesiones visibles.'], ['Vea a un médico en 14 días', 'El PIP de Florida lo exige. UrgiMed le atiende el mismo día y certifica su EMC.'], ['Notifique a su aseguradora', 'Abra un reclamo PIP antes de usar el seguro de salud. Facturamos al PIP directamente.'], ['Lleve un diario de síntomas', 'El dolor suele alcanzar su punto máximo 48–72 horas después.'], ['Siga su plan de tratamiento', 'Las interrupciones son lo primero que usa la aseguradora para disputar.']] } },
  'slip-and-fall': { services: ['xray', 'orthopedic', 'physical-therapy', 'chiropractic', 'pain-management'],
    symptoms: { en: ['Hip, wrist or tailbone pain', 'Swelling or bruising', 'Knee or ankle instability', 'Shoulder pain when lifting the arm', 'Headache after hitting your head', 'Back pain when standing'], es: ['Dolor de cadera, muñeca o coxis', 'Hinchazón o moretones', 'Inestabilidad de rodilla o tobillo', 'Dolor de hombro al levantar el brazo', 'Dolor de cabeza tras golpearse', 'Dolor de espalda al estar de pie'] },
    todo: { icons: ['flag', 'camera', 'users', 'steth'], en: [['Report the fall before leaving', 'Ask for a manager and an incident report.'], ['Photograph the hazard', 'Wet floor, broken step, missing sign — before it is fixed.'], ['Get witness names', 'A first name and phone number is enough.'], ['See a doctor the same day', 'A dated orthopedic exam with X-ray is the record your claim depends on.']], es: [['Reporte la caída antes de irse', 'Pida un gerente y un reporte de incidente.'], ['Fotografíe el peligro', 'Piso mojado, escalón roto, señal faltante, antes de que lo arreglen.'], ['Anote testigos', 'Un nombre y teléfono bastan.'], ['Vea a un médico el mismo día', 'Un examen ortopédico fechado con rayos X es el registro del que depende su reclamo.']] } },
  'work-injury': { services: ['orthopedic', 'xray', 'physical-therapy', 'chiropractic', 'pain-management', 'rom'],
    symptoms: { en: ['Lower back pain after lifting', 'Wrist or elbow pain from repetitive work', 'Shoulder pain overhead', 'Knee pain from kneeling or falls', 'Numbness in hands', 'Neck strain from desk work'], es: ['Dolor lumbar tras levantar peso', 'Dolor de muñeca o codo por trabajo repetitivo', 'Dolor de hombro al alzar el brazo', 'Dolor de rodilla por arrodillarse o caídas', 'Entumecimiento en las manos', 'Tensión de cuello por trabajo de escritorio'] },
    todo: { icons: ['file', 'steth', 'clipcheck', 'shield'], en: [['Report the injury in writing within 30 days', 'Florida law requires it; do it the same day.'], ['Ask for UrgiMed as your authorized physician', 'You can request a provider and are entitled to one change.'], ['Get the DWC forms completed', 'We complete DWC-25 after every visit and send work-status notes.'], ['Follow restrictions', 'Returning too early can reset your recovery and your claim.']], es: [['Reporte la lesión por escrito en 30 días', 'La ley de Florida lo exige; hágalo el mismo día.'], ['Pida UrgiMed como médico autorizado', 'Puede solicitar un proveedor y tiene derecho a un cambio.'], ['Complete los formularios DWC', 'Llenamos el DWC-25 en cada visita y enviamos notas de estado laboral.'], ['Respete las restricciones', 'Volver demasiado pronto puede retrasar su recuperación y su reclamo.']] } },
  'sports-injury': { services: ['orthopedic', 'xray', 'physical-therapy', 'prp', 'laser', 'chiropractic'],
    symptoms: { en: ['Knee swelling or giving way', 'Shoulder pain or weakness', 'Ankle sprain that will not heal', 'Elbow pain when gripping', 'Heel or foot pain in the morning', 'Hamstring or groin pull'], es: ['Rodilla hinchada o que falla', 'Dolor o debilidad de hombro', 'Esguince de tobillo que no sana', 'Dolor de codo al agarrar', 'Dolor de talón o pie por la mañana', 'Tirón de isquiotibiales o ingle'] },
    todo: { icons: ['ice', 'scan', 'activity', 'run'], en: [['Stop and protect the joint', 'Rest, ice, compression, elevation for the first 48 hours.'], ['Get imaged before returning to play', 'X-ray and ultrasound rule out fracture and tears.'], ['Start rehab early', 'Physical therapy within the first week shortens recovery.'], ['Ask about PRP', 'Regenerative injections for tendon and ligament injuries.']], es: [['Detenga la actividad y proteja la articulación', 'Reposo, hielo, compresión y elevación las primeras 48 horas.'], ['Hágase imágenes antes de volver a jugar', 'Rayos X y ultrasonido descartan fracturas y desgarros.'], ['Empiece la rehabilitación pronto', 'La terapia física en la primera semana acorta la recuperación.'], ['Pregunte por el PRP', 'Inyecciones regenerativas para tendones y ligamentos.']] } },
};
const SYMPTOMS = [
  { en: 'Neck pain or stiffness', es: 'Dolor o rigidez de cuello', inj: ['car-accident', 'work-injury'], svc: ['chiropractic', 'xray', 'physical-therapy'] },
  { en: 'Headaches or dizziness', es: 'Dolor de cabeza o mareos', inj: ['car-accident', 'slip-and-fall'], svc: ['neurology', 'chiropractic'] },
  { en: 'Back pain', es: 'Dolor de espalda', inj: ['car-accident', 'work-injury', 'slip-and-fall'], svc: ['chiropractic', 'pain-management', 'physical-therapy'] },
  { en: 'Numbness or tingling', es: 'Entumecimiento u hormigueo', inj: ['car-accident', 'work-injury'], svc: ['nerve', 'neurology', 'pain-management'] },
  { en: 'Shoulder pain', es: 'Dolor de hombro', inj: ['car-accident', 'sports-injury', 'work-injury'], svc: ['orthopedic', 'physical-therapy', 'prp'] },
  { en: 'Knee pain or swelling', es: 'Dolor o hinchazón de rodilla', inj: ['sports-injury', 'slip-and-fall', 'car-accident'], svc: ['orthopedic', 'xray', 'prp'] },
  { en: 'Wrist or hand pain', es: 'Dolor de muñeca o mano', inj: ['slip-and-fall', 'car-accident', 'work-injury'], svc: ['orthopedic', 'xray', 'nerve'] },
  { en: 'Hip or tailbone pain', es: 'Dolor de cadera o coxis', inj: ['slip-and-fall', 'car-accident'], svc: ['orthopedic', 'xray', 'physical-therapy'] },
  { en: 'Chest or rib pain', es: 'Dolor de pecho o costillas', inj: ['car-accident'], svc: ['xray', 'pain-management'] },
  { en: 'Brain fog or memory problems', es: 'Confusión mental o problemas de memoria', inj: ['car-accident', 'slip-and-fall'], svc: ['neurology', 'psychology'] },
  { en: 'Anxiety or fear of driving', es: 'Ansiedad o miedo a conducir', inj: ['car-accident'], svc: ['psychology'] },
  { en: 'Ankle or foot pain', es: 'Dolor de tobillo o pie', inj: ['sports-injury', 'slip-and-fall', 'work-injury'], svc: ['orthopedic', 'physical-therapy', 'laser'] },
];
Object.assign(window, { INJURY_EXTRA, SYMPTOMS });
